name: Ruby Scraper and Deploy

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Rubyのバージョン指定
          bundler-cache: true # bundle install を自動で行い、キャッシュする

      - name: Run Scraper
        run: bundle exec ruby scraper.rb

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # index.html が出力されたディレクトリ

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
